### PR TITLE
set bounds using leaflet

### LINKED ISSUE #65: Refactor set_viewpoint method
When updating tests, this method appears to be doing just too much. Perhaps this should be a class itself?

### PR DESCRIPTION
**Pull request by mejackreed**
Instead of trying to find the bounds using a helper method, can we just use the api that Leaflet already provides us?

Closes #65

### CODE REVIEW

**Comment by ebenenglish** [comment]
@mejackreed I like the idea of using Leaflet's API to set the viewpoint rather than the helper function. But, I don't think we should get rid of the ```viewpoint``` option in the data hash. We should still allow the implementation to designate a specific viewpoint if they want the map to be focused on specific bounds regardless of the features being passed to the map.

The use case for this would be something like http://dp.la/map, where the map is focused on the lower 48 United States, even though there are markers on Alaska and Hawaii.

So we still need to allow ```viewpoint``` to be passed to the ```blacklight_map_tag``` data hash, and we need to check for the presence of that value before calling the Leaflet ```fitBounds``` function.

**Comment by mejackreed** [comment]
@ebenenglish do you see that as new functionality or maintaining existing functionality?

Also how do we test it?

**Comment by mejackreed** [comment]
The reason I ask is I'm feeling this is probably best addressed with a js refactor that would be larger than this pr

**Comment by mejackreed** [comment]
Sorry one last question, do we need to use `viewpoint`? If not I would advocate for a term like `mapBounds` or `mapExtent` might be more appropriate.

**Comment by ebenenglish** [comment]
@mejackreed The ability to pass a viewpoint in the data hash is existing functionality, which is why I'm loathe to remove it.

A larger JS refactor wouldn't be out of the question, and might be useful. I'm open to further discussion on this. However, I think maintaining the support for setting the viewpoint in the data hash wouldn't be much of an imposition to add to this PR.

I suppose we could use a different term besides ```viewpoint``` --  I thought this was what they called in the Leaflet API docs, but I'm not finding any reference to that term now that I look closer. (Although they don't use ```mapBounds``` or ```mapExtent``` either...). The Leaflet API docs describe the ```setView``` function as: 
```
Sets the view of the map (geographical center and zoom) with the given animation options.
```
Would something like ```setViewParams``` be too awful? Let me know which way you're leaning...

**Comment by ebenenglish** [comment]
@mejackreed Also, in terms of testing, you could potentially add a test marker to the map, then set the ```setView``` params such that that marker would not be visible, then test for the lack of any marker ```div``` in the HTML?

**Comment by mejackreed** [comment]
Does the `viewpoint` parameter need to accommodate both a centerpoint and bounding box? Is one or the other sufficient?

**Comment by ebenenglish** [comment]
I guess the parameter just needs to accept a Leaflet ```LatLngBounds``` object in the form of an array of length=2 whose members are themselves coordinate point arrays:

http://leafletjs.com/reference.html#map-fitbounds
http://leafletjs.com/reference.html#latlngbounds

**Comment by mejackreed** [comment]
@ebenenglish This should be good to go now. I also updated the README to use a table for the JavaScript options. I feel like this is more readable.

Coveralls also gets fixed here: #72 .... so once that gets merged things should start reporting accurately.

**Pull request merged**
