### PR TITLE
update travis.yml to match blacklight

### PR DESCRIPTION
**Pull request by ebenenglish**
Update travis.yml to match Blacklight settings. As discussed in https://github.com/projectblacklight/blacklight-maps/pull/77.

### CODE REVIEW

**Comment by jrochkind** [comment]
You've taken out testing on JRuby.  It looks like Blacklight has too. I'm not sure if it's intentional, as JRuby is still mentioned as an allowed failure -- but testing isn't being done on JRuby at all, I think. The [latest travis](https://travis-ci.org/projectblacklight/blacklight/builds/84977381) from Blacklight confirms that there appears to be no Jruby build.

**Comment by mejackreed** [comment]
Looks like it. I'm curious why we don't do that on Blacklight?

**Comment by jrochkind** [comment]
Hm, I also could be wrong, maybe travis allowed_failures is actually a directive to test that thing too? I'm confused maybe?

**Comment by ebenenglish** [comment]
@jrochkind I think you're correct -- it would seem that builds in the ```allow failures``` block don't automatically get built, even though they're in the ```matrix``` block? This change was made in Blacklight here: https://github.com/projectblacklight/blacklight/pull/1217.

Of course, if JRuby fails on every build, and we're allowing it to fail, not sure why it needs to be kept in the build matrix? I have less CI experience than many in the BL community though, so if there's a good explanation we can add JRuby back in.

**Comment by jrochkind** [comment]
I don't know why Jruby was being allowed to fail anyway, either. The comment on allowing JRuby to fail is "until Jruby 9k comes out". Jruby 9k is out.

**Pull request merged**
