### PR TITLE
map should zoom to correct bounds if only feature is a bbox

### PR DESCRIPTION
**Pull request by ebenenglish**
This PR addresses https://github.com/projectblacklight/blacklight-maps/issues/76. 

Also moved specs for catalog#show maplet view to a dedicated file (with some additions) to address https://github.com/projectblacklight/blacklight-maps/issues/66.

### CODE REVIEW

**Comment by ebenenglish** [comment]
Build fails on Ruby 2.0.0. Should we continue to maintain support for this? At this point, Blacklight only tests 2.1.6, 2.2.2, and 2.2.3.

**Comment by mejackreed** [comment]
I think we should track with what Blacklight is doing... maybe a separate pr for that?

**Comment by ebenenglish** [comment]
OK. So maybe merge this one as is, then create a PR to modify the travis.yml? Or fix travis.yml in a separate PR first?

**Comment by mejackreed** [comment]
I think fix travis first, and then rebase master after that is merged

**Comment by ebenenglish** [comment]
@mejackreed Are we cool to merge this?

**Pull request merged**
