### PR TITLE
Add French locale file

### PR DESCRIPTION
**Pull request by ggeisler**
Adds a French locale file and just a couple of translations (ones needed for Spotlight).

### CODE REVIEW

**Comment by ebenenglish** [comment]
Hi @ggeisler I merged this, updated the gem version, and created a new release (0.5.2). However I don't have the permissions to push to rubygems.org, can you do this? (Or make me an owner in rubygems? Same username as github.) Thanks!

**Comment by mejackreed** [comment]
@ebenenglish You should have the permissions now as an owner. Sorry about that!

**Comment by ggeisler** [comment]
@ebenenglish Sorry for the delay; I don't have permissions on rubygems so asked Jack to do it. Thanks for dealing with this PR so quickly!

**Comment by ebenenglish** [comment]
OK, thanks for the permissions update. Released 0.5.2!

**Pull request merged**
